apiVersion: v1 
kind: Service
metadata: 
  name: {{ .Release.Name }}-voting-service
  labels:
    app: demo-voting-app
spec: 
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: voting-app-pod
    app: demo-voting-app

---

apiVersion: v1 
kind: Service
metadata: 
  name: {{ .Release.Name }}-redis
  labels:
    app: demo-voting-app
spec: 
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-pod
    app: demo-voting-app

---

apiVersion: v1 
kind: Service
metadata: 
  name: {{ .Release.Name }}-db
  labels:
    app: demo-voting-app
spec: 
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app

---

apiVersion: v1 
kind: Service
metadata: 
  name: {{ .Release.Name }}-result-service
  labels:
    app: demo-voting-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: result-app-pod
    app: demo-voting-app